import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'QuizAI',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html className="bg-rose-100 text-rose-600" lang="en">
      <body className={inter.className}>
        <div className="flex flex-col items-center justify-center h-svh w-svh">
          {children}
        </div>
      </body>
    </html>
  )
}
